// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lambda_gen
List lambda_gen(NumericMatrix X, NumericVector y, int K);
RcppExport SEXP _ImbLassoRcpp_lambda_gen(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(lambda_gen(X, y, K));
    return rcpp_result_gen;
END_RCPP
}
// linear_lasso
void linear_lasso();
RcppExport SEXP _ImbLassoRcpp_linear_lasso() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    linear_lasso();
    return R_NilValue;
END_RCPP
}
// logistic_lasso
void logistic_lasso();
RcppExport SEXP _ImbLassoRcpp_logistic_lasso() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    logistic_lasso();
    return R_NilValue;
END_RCPP
}
// smote_minor_x
List smote_minor_x(const NumericMatrix& X, const int& k, const int& N);
RcppExport SEXP _ImbLassoRcpp_smote_minor_x(SEXP XSEXP, SEXP kSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int& >::type k(kSEXP);
    Rcpp::traits::input_parameter< const int& >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(smote_minor_x(X, k, N));
    return rcpp_result_gen;
END_RCPP
}
// stratified_cv
List stratified_cv(const NumericVector& y, const int& k);
RcppExport SEXP _ImbLassoRcpp_stratified_cv(SEXP ySEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int& >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(stratified_cv(y, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ImbLassoRcpp_lambda_gen", (DL_FUNC) &_ImbLassoRcpp_lambda_gen, 3},
    {"_ImbLassoRcpp_linear_lasso", (DL_FUNC) &_ImbLassoRcpp_linear_lasso, 0},
    {"_ImbLassoRcpp_logistic_lasso", (DL_FUNC) &_ImbLassoRcpp_logistic_lasso, 0},
    {"_ImbLassoRcpp_smote_minor_x", (DL_FUNC) &_ImbLassoRcpp_smote_minor_x, 3},
    {"_ImbLassoRcpp_stratified_cv", (DL_FUNC) &_ImbLassoRcpp_stratified_cv, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_ImbLassoRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
