# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'calculate the entry level of lambda
#'
#'Calculate the smallest value for which all the beta equal to 0.
#'
#'@name lambda_gen
#'
#'@param X input matrix, of dimension nobs x nvars; each row is an observation vector.
#'@param y binary response variable, positive outcome = 1 and negative outcome = 0.
#'@param K number of lambdas, by default is 100.
#'
#'@return A number
#'
#'
#'@export
NULL

lambda_gen <- function(X, y, K = 100L) {
    .Call('_ImbLassoRcpp_lambda_gen', PACKAGE = 'ImbLassoRcpp', X, y, K)
}

linear_lasso <- function() {
    invisible(.Call('_ImbLassoRcpp_linear_lasso', PACKAGE = 'ImbLassoRcpp'))
}

logistic_lasso <- function() {
    invisible(.Call('_ImbLassoRcpp_logistic_lasso', PACKAGE = 'ImbLassoRcpp'))
}

#'SMOTE algorithm for minority class
#'
#'This function generates synthetic examples for the minority class by kNN and interpolation
#'
#'Add details
#'
#'@name smote_minor_x
#'
#'@param X feature matrix
#'@param k number of nearest neighbors to be considered, default value is 5
#'@param N number of new synthetic examples to be generated for each observation, default value is 9
#'
#'@return A list including new synthetic examples with \code{N*nrow(X)} rows and \code{ncol(X)} columns.
#'
#'
#'@export
NULL

smote_minor_x <- function(X, k = 5L, N = 9L) {
    .Call('_ImbLassoRcpp_smote_minor_x', PACKAGE = 'ImbLassoRcpp', X, k, N)
}

#'Stratified cross-validation sampling
#'
#'This function assigns observations to k-fold cross validation.
#'
#'Add details
#'
#'@name stratified_cv
#'
#'@param y binary outcome, where 1 = positive event and 0 = negative event
#'@param k number of folds, default value is 10
#'
#'@return A list including new synthetic examples with \code{N*nrow(X)} rows and \code{ncol(X)} columns.
#'
#'
#'@export
#' @examples
#' stratified_cv(rbinom(2023, 1, 0.1), 10)
stratified_cv <- function(y, k = 10L) {
    .Call('_ImbLassoRcpp_stratified_cv', PACKAGE = 'ImbLassoRcpp', y, k)
}

